export const wineList = [
    {
        id: 1,
        name: 'Kendall Jackson',
        grape: 'Chardonnay',
        type: 'white',
        vintage: '2020',
        price: 21.49,
        country: 'California, US',
        driness: 'dry',
        sweetness: 'sweet',
        recommend: true,
        image: './images/kendall_jackson_chardonnay.png',
        link: ''
    },
    {
        id: 2,
        name: 'Hardys',
        grape: 'Shiraz',
        type: 'red',
        vintage: '2018',
        price: 11.98,
        country: 'Hardys, South Eastern Australia',
        driness: 'dry',
        sweetness: 'sweet',
        recommend: true,
        image: './images/hardys_shiraz.png',
        link: ''
    },
    {
        id: 3,
        name: 'Kung Fu Girl',
        grape: 'Riesling',
        type: 'white',
        vintage: '2017',
        price: 19.98,
        country: 'Washington, US',
        driness: 'dry',
        sweetness: 'sweet',
        recommend: false,
        image: './images/kung_fu_girl_riesling.png',
        link: ''
    },
    {
        id: 4,
        name: 'Damilano',
        grape: 'Nebbiolo',
        type: 'red',
        vintage: '2018',
        price: 36.99,
        country: 'Italy',
        driness: 'dry',
        sweetness: 'sweet',
        recommend: true,
        image: './images/damilano_nebbiolo.png',
    },
    {
        id: 5,
        name: 'Napa Paradise Cellars',
        grape: 'Cabernet Sauvignon',
        type: 'red',
        vintage: '',
        price: 41.54,
        country: 'Napa Valley, US',
        driness: 'dry',
        sweetness: 'sweet',
        recommend: true,
        image: './images/napa_paradise_cellars_cabernet_sauvignon.jpg',
    },
    {
        id: 6,
        name: 'Chateau Ste. Michelle',
        grape: 'Riesling',
        type: 'white',
        vintage: '',
        price: 24.90,
        country: 'Columbia Valley, US',
        driness: 'dry',
        sweetness: 'sweet',
        recommend: true,
        image: './images/chateau_ste_michelle_riesling.png',
    },
    {
        id: 7,
        name: '19 Crimes',
        grape: 'Cabernet Sauvignon',
        type: 'red',
        vintage: '',
        price: 29.49,
        country: 'Victoria, Australia',
        driness: 'dry',
        sweetness: 'sweet',
        recommend: true,
        image: './images/19_crimes_cabernet_sauvignon.png',
    },
    {
        id: 8,
        name: 'Two Hands',
        grape: 'Shiraz',
        type: 'red',
        vintage: '',
        price: 64.39,
        country: 'McLaren Vale, Australia',
        driness: 'dry',
        sweetness: 'sweet',
        recommend: true,
        image: './images/19_crimes_cabernet_sauvignon.png',
        link: 'https://www.vivino.com/CA/en/two-hands-wines-angels-share-shiraz/w/6168?ref=nav-search'
    }
];

export default wineList;